### ISSUE TITLE
mathjax support?

### ISSUE THREAD

**Issue by avivajpeyi** [sharm294/sphinx-datatables#1]
Any suggestions on how to use this with mathjax?  Eg: 
```

.. csv-table::
    :header: $m_1$, $m_2$
    :class: sphinx-datatable

    John,$1_{+1}_{-1}$
    Jane,Doe
```

Id like to render something like the following: 
<img width="894" alt="Screen Shot 2023-09-12 at 5 30 32 pm" src="https://github.com/sharm294/sphinx-datatables/assets/15642823/26d1c56e-b557-4bad-8492-990cd6aa27b3">

**Comment by sharm294** [comment]
Based on the Sphinx documentation, I believe you'll have to use LaTeX syntax for math. You can use [directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#math) or [roles](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-math) to specify it. There appears to be a [MathJax plugin](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax) but even that says that you have to use the directives and roles, not native MathJax syntax.

E.g.

![image](https://github.com/sharm294/sphinx-datatables/assets/29899983/684a342c-1c99-4de7-a7a1-34d9f1adf4c2)

from

```
.. csv-table::
    :header: :math:`m_1`, :math:`m_2`
    :class: sphinx-datatable

    John,:math:`{1_{+1}}_{-1}`
    Jane,Doe
```
