### ISSUE TITLE
Internationalisation plug-ins?

### ISSUE THREAD

**Issue by dbitouze** [sharm294/sphinx-datatables#2]
Many thanks for `sphinx-datatables`!

Would it be possible for `sphinx-datatables` to enable `DataTables` [internationalization plug-ins](https://datatables.net/plug-ins/i18n/)?

**Comment by sharm294** [comment]
Hi @dbitouze, thanks for the issue. Apologies for the late reply but I've enabled this option. Check out the [docs](https://sharm294.github.io/sphinx-datatables/#custom-options).
